### ISSUE TITLE
Addresses with.dot.@before.at fails, mail returns string, not array of recipients

### ISSUE THREAD

**Issue by holli** [cerebris/mailhopper#7]
Creating a email with a bit weirder format so that mail cannot parse it well results in error in delivering.

Try creating email, then setting

```
@email = SomeEmail()
@email.to = "bogus@hotmail.com"
@email.to # returns ["bogus@hotmail.com"]
@email.to = "bogus.@hotmail.com"
@email.to # returns bogus.@hotmail.com, string, not an array
@email.deliver # delivering with mailhopper fails
```

Results in error error

```
undefined method `join' for "bogus.@hotmail.com":String

mailhopper (0.0.9) lib/mailhopper/queue.rb:21:in `address_to_s'
mailhopper (0.0.9) lib/mailhopper/queue.rbin `deliver!'
...
```

Easiest fix would be probably to fix address_to_s(field) method:
https://github.com/cerebris/mailhopper/blob/master/lib/mailhopper/queue.rb#L21

to begin with `return field if field.is_a?(String)`

**Comment by dgeb** [comment]
Thanks for reporting this. So this will occur for `bogus.@hotmail.com`, but not `bogus.address@hotmail.com`? In other words, the dot must immediately precede the @ symbol?

**Comment by dgeb** [comment]
Fixed in v0.1.1

**Comment by holli** [comment]
Whoa, thanks, that was a quick fix again :)

I'm not sure if the dot has to be just before @ symbol. Its more of an issue if the email addresses are kind of "invalid" and mail gem can't parse them, then it will return the original string instead of parsed arrays. So probably if you have something like asdf@asdf@hotmail.com it would return a string instead of array.

**Comment by dgeb** [comment]
Thanks - that's what I suspected. It should pass through any addresses, bogus or not, that you throw at it now.
