### ISSUE TITLE
This isn't so much an issue as a suggestion

### ISSUE THREAD

**Issue by brightball** [cerebris/mailhopper#9]
Since Mailhopper already nicely handles storing emails in the database and sending them via DJ/Resque, it would be great if there was a clean way to integrate with something like this:

https://github.com/aceofspades/sendgrid_postback

That gem tracks delivery information (bounces, spam reports, invalid emails, etc) via sendgrid postbacks but it's just using a simple MailObserver to actually save the records and the UUID needed to map the postbacks to the send message.  If there was a clean way to map that data into the existing Mailhopper records...well that would be slick.

**Comment by brightball** [comment]
Also, you can close this out.  I'm working on a fork of sendgrid_postback to do exactly what I've described.  This, coupled with https://github.com/cerebris/mailhopper/issues/6 has made it possible to queue emails, send them, and track deliverability all in one place.  I'll shoot over a link to the working code when it's ready.

**Comment by dgeb** [comment]
@aramisbear - Sounds good. I'll close this for now, but please follow up when you're ready.
